"""Paper per DOI (ADR-0016, PRD #137 Teil B): the core intake endpoint.

Creation, DOI dedup, the list form, the exists batch, and the two network
seams — enrichment and the best-effort OA PDF — with OpenAlex/the PDF host
mocked via respx and CrossRef via patch (it speaks ``requests``).
"""
from __future__ import annotations

from unittest.mock import patch

import httpx
import pytest
import respx

import metadata_validation
import paper_ingest
from openalex_client import BASE_URL

PDF_BYTES = b"%PDF-1.4 fake open-access pdf"


def _row(db, paper_id):
    conn = db._connect()
    try:
        return dict(conn.execute("SELECT * FROM papers WHERE id = ?", (paper_id,)).fetchone())
    finally:
        conn.close()


def _work(doi, pdf_url="", **extra):
    return {
        "id": "https://openalex.org/W1",
        "doi": f"https://doi.org/{doi}",
        "title": extra.get("title", "OA Werk"),
        "authorships": [{"author": {"display_name": n}} for n in extra.get("authors", [])],
        "publication_year": extra.get("year"),
        "cited_by_count": 3,
        "referenced_works": [],
        "abstract_inverted_index": extra.get("abstract_index"),
        "best_oa_location": {"pdf_url": pdf_url, "landing_page_url": ""} if pdf_url else None,
        "open_access": {"oa_url": ""},
    }


def test_create_stores_metadata_and_origin(client, db):
    resp = client.post("/api/papers/by-doi", json={
        "doi": "https://doi.org/10.5555/Intake.1",
        "title": "Robotic clay printing", "authors": ["Doe, Jane", "Roe, Rob"],
        "year": 2026, "journal": "AiC", "abstract": "Ein Abstract.", "source": "trend-plugin",
    })
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["created"] is True
    assert body["pdf"] == "none"
    assert body["doi"] == "10.5555/intake.1"
    row = _row(db, body["paper_id"])
    assert row["title"] == "Robotic clay printing"
    assert row["authors"] == "Doe, Jane; Roe, Rob"
    assert row["year"] == 2026
    assert row["journal"] == "AiC"
    assert row["abstract"] == "Ein Abstract."
    assert row["doi"] == "10.5555/intake.1"
    assert row["import_source"] == "trend-plugin"
    assert row["filename"] == ""
    assert row["cite_key"]  # generated by add_paper


def test_existing_doi_answers_with_its_id_and_created_false(client, db):
    first = client.post("/api/papers/by-doi", json={"doi": "10.5555/dup", "title": "A"}).json()
    second = client.post("/api/papers/by-doi", json={"doi": "  10.5555/DUP ", "title": "B"}).json()
    assert second["created"] is False
    assert second["paper_id"] == first["paper_id"]
    assert _row(db, first["paper_id"])["title"] == "A"  # untouched


def test_authors_may_be_a_joined_string(client, db):
    body = client.post("/api/papers/by-doi", json={
        "doi": "10.5555/str", "authors": "Doe, Jane; Roe, Rob"}).json()
    assert _row(db, body["paper_id"])["authors"] == "Doe, Jane; Roe, Rob"


def test_empty_doi_is_400(client, db):
    assert client.post("/api/papers/by-doi", json={"doi": "  "}).status_code == 400


def test_batch_reports_per_item(client, db):
    client.post("/api/papers/by-doi", json={"doi": "10.5555/have", "title": "Have"})
    resp = client.post("/api/papers/by-doi/batch", json={"items": [
        {"doi": "10.5555/new1", "title": "New 1"},
        {"doi": "10.5555/have", "title": "Have again"},
        {"doi": "", "title": "no doi"},
    ]})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["total"] == 3
    assert body["created"] == 1
    assert body["existing"] == 1
    assert body["errors"] == 1
    new, have, bad = body["results"]
    assert new["created"] is True and new["paper_id"]
    assert have["created"] is False and have["paper_id"]
    assert bad["paper_id"] is None and bad["error"]


def test_exists_batch_maps_each_doi_to_id_or_null(client, db):
    pid = client.post("/api/papers/by-doi", json={"doi": "10.5555/x", "title": "X"}).json()["paper_id"]
    resp = client.post("/api/papers/by-doi/exists", json={
        "dois": ["10.5555/X", "https://doi.org/10.5555/x", "10.5555/unknown", ""]})
    assert resp.status_code == 200, resp.text
    papers = resp.json()["papers"]
    assert papers["10.5555/X"] == pid
    assert papers["https://doi.org/10.5555/x"] == pid
    assert papers["10.5555/unknown"] is None
    assert "" not in papers


@pytest.mark.real_enrichment
@respx.mock
def test_enrichment_fills_empty_fields_from_crossref_and_openalex(client, db):
    respx.get(f"{BASE_URL}/works").mock(return_value=httpx.Response(200, json={
        "results": [_work("10.5555/enrich", authors=["Neu, Nina"], year=2022)]}))
    with patch.object(metadata_validation, "fetch_crossref_abstract",
                      return_value="Ein Abstract aus CrossRef."):
        resp = client.post("/api/papers/by-doi", json={"doi": "10.5555/enrich", "title": "Nackt"})
    assert resp.status_code == 200, resp.text
    row = _row(db, resp.json()["paper_id"])
    assert row["abstract"] == "Ein Abstract aus CrossRef."
    assert row["year"] == 2022
    assert row["authors"] == "Neu, Nina"


@pytest.mark.real_enrichment
@respx.mock
def test_failed_oa_attempt_keeps_the_paper_and_reports_pdf_none(client, db):
    respx.get(f"{BASE_URL}/works").mock(return_value=httpx.Response(200, json={
        "results": [_work("10.5555/oafail", pdf_url="https://repo.example.org/gone.pdf")]}))
    respx.get("https://repo.example.org/gone.pdf").mock(return_value=httpx.Response(500))
    with patch.object(metadata_validation, "fetch_crossref_abstract", return_value=""):
        resp = client.post("/api/papers/by-doi", json={"doi": "10.5555/oafail", "title": "Fail"})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["created"] is True
    assert body["pdf"] == "none"
    assert _row(db, body["paper_id"])["filename"] == ""


@pytest.mark.real_enrichment
@respx.mock
def test_oa_pdf_is_fetched_and_attached(client, db):
    respx.get(f"{BASE_URL}/works").mock(return_value=httpx.Response(200, json={
        "results": [_work("10.5555/oaok", pdf_url="https://repo.example.org/ok.pdf")]}))
    respx.get("https://repo.example.org/ok.pdf").mock(return_value=httpx.Response(
        200, content=PDF_BYTES, headers={"content-type": "application/pdf"}))
    with patch.object(metadata_validation, "fetch_crossref_abstract", return_value=""), \
         patch.object(paper_ingest, "categorize_with_llm", return_value=[]), \
         patch.object(paper_ingest, "extract_text_from_pdf", return_value="Volltext"):
        resp = client.post("/api/papers/by-doi", json={"doi": "10.5555/oaok", "title": "OK"})
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["created"] is True
    assert body["pdf"] == "fetched"
    row = _row(db, body["paper_id"])
    assert row["filename"].endswith(".pdf")
    assert row["ocr_text"] == "Volltext"

    # Asking again: existing, and the PDF state reflects the file.
    again = client.post("/api/papers/by-doi", json={"doi": "10.5555/oaok"}).json()
    assert again["created"] is False
    assert again["pdf"] == "fetched"
